meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: glances
    templates:
    - name: glances
      release: glances
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties: {}
